FROM python:3.10

WORKDIR /code

RUN pip install \
    --no-cache-dir \
    --upgrade \
    fastapi uvicorn sqlalchemy opentelemetry-distro opentelemetry-exporter-otlp
    # fastapi uvicorn sqlalchemy opentelemetry-distro opentelemetry-exporter-otlp opentelemetry-instrumentation-fastapi opentelemetry-instrumentation-sqlalchemy opentelemetry-instrumentation-asgi opentelemetry-instrumentation-logging

RUN opentelemetry-bootstrap -a install

COPY ./prog /code/prog

ENV OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
ENV OTEL_EXPORTER_OTLP_INSECURE=true

CMD opentelemetry-instrument \
    --traces_exporter console \
    --metrics_exporter console \
    --logs_exporter console \
    --service_name prog-otel-app \
    uvicorn prog.main:app --host 0.0.0.0 --port 8000
