# Collector configuration reference
# https://opentelemetry.io/docs/collector/configuration/

extensions:
  zpages:
    endpoint: 0.0.0.0:55679

# receivers reference
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

# exporters reference
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter
exporters:
  debug:
    verbosity: detailed
  logging:
    verbosity: detailed

  # tracing
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    tls:
      insecure: true
  elasticsearch/trace:  # export directly to elasticsearch
    endpoints: [http://elasticsearch:9200]
    traces_index: otel_trace_index
  otlp: 
    # Elastic APM server https endpoint without the "https://" prefix
    # Handled by Elastic Observability
    endpoint: apm-server:8200
    tls:
      insecure: true

  # log
  elasticsearch/log:  # export directly to elasticsearch
    endpoints: [http://elasticsearch:9200]
    logs_index: otel_log_index
    sending_queue:
      enabled: true
      num_consumers: 20
      queue_size: 1000
  
  # metrics
  prometheus:  # expose metrics in prometheus format at otel collector
    endpoint: otel_collector:8889
    metric_expiration: 180m
    const_labels:
      env: test
  prometheusremotewrite:  # push metrics to prometheus
    endpoint: http://prometheus:9090/api/v1/write
    tls:
      insecure: true
    external_labels:
      env: demo

processors:
  batch:

# https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md
service:
  telemetry:
    logs:
      level: "debug"
    metrics:
      address: ":8888"  # otel collector metrics prometheus format exposed at /metrics
      level: detailed

  extensions:
    - zpages

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, zipkin, otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, elasticsearch/log]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, prometheusremotewrite, otlp]
